apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/backend

patches:
  - target:
      kind: Service
      name: backend
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
